- name: yum install bacepackage
  yum: name={{ item }} state=present
  with_items:
    - vim
    - zsh
    - git
    - tree
    - htop
    - mlocate
    - telnet
    - yum-plugin-changelog


- name: change timezone to Asia/Tokyo
  timezone:
    name: Asia/Tokyo
