- name: install remi
  yum: name={{ item }} state=present
  with_items:
    - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm"
    - "http://rpms.famillecollet.com/enterprise/remi-release-6.rpm"

- name: install php base
  yum: name={{ item }} state=present disablerepo=amzn-main enablerepo=epel
  with_items:
    - libwebp

- name: install php dependency module
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - libmcrypt
    - libtool-ltdl
    - libtidy
    - libXpm
    - libtiff
    - autoconf
    - automake
    - gd-last
    - enchant-aspell

- name: install php
  yum: name={{ item }} state=present enablerepo=remi,remi-php70 disablerepo=amzn-main
  with_items:
    - php
    - php-fpm

- name: service start php-fpm
  service: name=php-fpm state=started enabled=yes
